// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: fav.proto

package __FavProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fav_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_fav_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_fav_proto_rawDescGZIP(), []int{0}
}

type UserFavRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int32 `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
}

func (x *UserFavRequest) Reset() {
	*x = UserFavRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fav_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFavRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavRequest) ProtoMessage() {}

func (x *UserFavRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fav_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavRequest.ProtoReflect.Descriptor instead.
func (*UserFavRequest) Descriptor() ([]byte, []int) {
	return file_fav_proto_rawDescGZIP(), []int{1}
}

func (x *UserFavRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFavRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type UserFavResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int32 `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
}

func (x *UserFavResponse) Reset() {
	*x = UserFavResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fav_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFavResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavResponse) ProtoMessage() {}

func (x *UserFavResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fav_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavResponse.ProtoReflect.Descriptor instead.
func (*UserFavResponse) Descriptor() ([]byte, []int) {
	return file_fav_proto_rawDescGZIP(), []int{2}
}

func (x *UserFavResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFavResponse) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type UserFavListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*UserFavResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UserFavListResponse) Reset() {
	*x = UserFavListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fav_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFavListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFavListResponse) ProtoMessage() {}

func (x *UserFavListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fav_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFavListResponse.ProtoReflect.Descriptor instead.
func (*UserFavListResponse) Descriptor() ([]byte, []int) {
	return file_fav_proto_rawDescGZIP(), []int{3}
}

func (x *UserFavListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserFavListResponse) GetData() []*UserFavResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_fav_proto protoreflect.FileDescriptor

var file_fav_proto_rawDesc = []byte{
	0x0a, 0x09, 0x66, 0x61, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x66, 0x61, 0x76,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x42, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x61, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x43, 0x0a,
	0x0f, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x64, 0x22, 0x55, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x66, 0x61, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xd8, 0x01, 0x0a, 0x03, 0x46, 0x61,
	0x76, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x61, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x13, 0x2e, 0x66, 0x61, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x61, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x61, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d,
	0x0a, 0x0a, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x12, 0x13, 0x2e, 0x66,
	0x61, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x2e, 0x66, 0x61, 0x76, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x30, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x12, 0x13,
	0x2e, 0x66, 0x61, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x66, 0x61, 0x76, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x33, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x13, 0x2e, 0x66, 0x61, 0x76, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61,
	0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x66, 0x61, 0x76, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x46, 0x61, 0x76, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fav_proto_rawDescOnce sync.Once
	file_fav_proto_rawDescData = file_fav_proto_rawDesc
)

func file_fav_proto_rawDescGZIP() []byte {
	file_fav_proto_rawDescOnce.Do(func() {
		file_fav_proto_rawDescData = protoimpl.X.CompressGZIP(file_fav_proto_rawDescData)
	})
	return file_fav_proto_rawDescData
}

var file_fav_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fav_proto_goTypes = []any{
	(*Empty)(nil),               // 0: fav.Empty
	(*UserFavRequest)(nil),      // 1: fav.UserFavRequest
	(*UserFavResponse)(nil),     // 2: fav.UserFavResponse
	(*UserFavListResponse)(nil), // 3: fav.UserFavListResponse
}
var file_fav_proto_depIdxs = []int32{
	2, // 0: fav.UserFavListResponse.data:type_name -> fav.UserFavResponse
	1, // 1: fav.Fav.GetFavList:input_type -> fav.UserFavRequest
	1, // 2: fav.Fav.AddUserFav:input_type -> fav.UserFavRequest
	1, // 3: fav.Fav.DeleteUserFav:input_type -> fav.UserFavRequest
	1, // 4: fav.Fav.GetUserFavDetail:input_type -> fav.UserFavRequest
	3, // 5: fav.Fav.GetFavList:output_type -> fav.UserFavListResponse
	0, // 6: fav.Fav.AddUserFav:output_type -> fav.Empty
	0, // 7: fav.Fav.DeleteUserFav:output_type -> fav.Empty
	0, // 8: fav.Fav.GetUserFavDetail:output_type -> fav.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fav_proto_init() }
func file_fav_proto_init() {
	if File_fav_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fav_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fav_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserFavRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fav_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UserFavResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fav_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UserFavListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fav_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fav_proto_goTypes,
		DependencyIndexes: file_fav_proto_depIdxs,
		MessageInfos:      file_fav_proto_msgTypes,
	}.Build()
	File_fav_proto = out.File
	file_fav_proto_rawDesc = nil
	file_fav_proto_goTypes = nil
	file_fav_proto_depIdxs = nil
}
